{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "856dabd7-fd17-40c7-a429-49974b85767c",
   "metadata": {},
   "outputs": [
    {
     "ename": "ModuleNotFoundError",
     "evalue": "No module named 'TTS'",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mModuleNotFoundError\u001b[0m                       Traceback (most recent call last)",
      "Cell \u001b[1;32mIn[3], line 20\u001b[0m\n\u001b[0;32m     17\u001b[0m MODEL_NAME \u001b[38;5;241m=\u001b[39m os\u001b[38;5;241m.\u001b[39mgetenv(\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mMODEL_NAME\u001b[39m\u001b[38;5;124m\"\u001b[39m, \u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mtts_models/multilingual/multi-dataset/xtts_v2\u001b[39m\u001b[38;5;124m\"\u001b[39m)\n\u001b[0;32m     18\u001b[0m DEVICE \u001b[38;5;241m=\u001b[39m os\u001b[38;5;241m.\u001b[39mgetenv(\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mDEVICE\u001b[39m\u001b[38;5;124m\"\u001b[39m, \u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mcuda\u001b[39m\u001b[38;5;124m\"\u001b[39m \u001b[38;5;28;01mif\u001b[39;00m os\u001b[38;5;241m.\u001b[39mgetenv(\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mCUDA_VISIBLE_DEVICES\u001b[39m\u001b[38;5;124m\"\u001b[39m, \u001b[38;5;124m\"\u001b[39m\u001b[38;5;124m\"\u001b[39m) \u001b[38;5;241m!=\u001b[39m \u001b[38;5;124m\"\u001b[39m\u001b[38;5;124m\"\u001b[39m \u001b[38;5;28;01melse\u001b[39;00m \u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mcpu\u001b[39m\u001b[38;5;124m\"\u001b[39m)\n\u001b[1;32m---> 20\u001b[0m \u001b[38;5;28;01mfrom\u001b[39;00m\u001b[38;5;250m \u001b[39m\u001b[38;5;21;01mTTS\u001b[39;00m\u001b[38;5;21;01m.\u001b[39;00m\u001b[38;5;21;01mapi\u001b[39;00m\u001b[38;5;250m \u001b[39m\u001b[38;5;28;01mimport\u001b[39;00m TTS\n\u001b[0;32m     21\u001b[0m tts \u001b[38;5;241m=\u001b[39m TTS(MODEL_NAME)\u001b[38;5;241m.\u001b[39mto(DEVICE)\n\u001b[0;32m     23\u001b[0m \u001b[38;5;66;03m# try to read sample rate from model; fall back to common value\u001b[39;00m\n",
      "\u001b[1;31mModuleNotFoundError\u001b[0m: No module named 'TTS'"
     ]
    }
   ],
   "source": [
    "import asyncio\n",
    "import base64\n",
    "import io\n",
    "import os\n",
    "import uuid\n",
    "from typing import Optional\n",
    "\n",
    "import numpy as np\n",
    "import soundfile as sf\n",
    "from fastapi import FastAPI, UploadFile, File, Form, WebSocket, WebSocketDisconnect\n",
    "from fastapi.middleware.cors import CORSMiddleware\n",
    "from fastapi.responses import Response, JSONResponse\n",
    "from pydantic import BaseModel\n",
    "\n",
    "# ---- Model load ----\n",
    "# XTTS v2 model name from Coqui TTS\n",
    "MODEL_NAME = os.getenv(\"MODEL_NAME\", \"tts_models/multilingual/multi-dataset/xtts_v2\")\n",
    "DEVICE = os.getenv(\"DEVICE\", \"cuda\" if os.getenv(\"CUDA_VISIBLE_DEVICES\", \"\") != \"\" else \"cpu\")\n",
    "\n",
    "from TTS.api import TTS\n",
    "tts = TTS(MODEL_NAME).to(DEVICE)\n",
    "\n",
    "# try to read sample rate from model; fall back to common value\n",
    "def get_sample_rate() -> int:\n",
    "    for attr in (\"output_sample_rate\",):\n",
    "        if hasattr(tts, attr):\n",
    "            return getattr(tts, attr)\n",
    "    if hasattr(tts, \"synthesizer\") and hasattr(tts.synthesizer, \"output_sample_rate\"):\n",
    "        return tts.synthesizer.output_sample_rate\n",
    "    return 24000\n",
    "\n",
    "SAMPLE_RATE = get_sample_rate()\n",
    "\n",
    "# Serialize audio to WAV bytes\n",
    "def audio_to_wav_bytes(audio: np.ndarray, sr: int = SAMPLE_RATE) -> bytes:\n",
    "    # ensure float32 mono\n",
    "    audio = audio.astype(np.float32)\n",
    "    buf = io.BytesIO()\n",
    "    sf.write(buf, audio, sr, format=\"WAV\")\n",
    "    return buf.getvalue()\n",
    "\n",
    "# simple concurrency guard (GPU-friendly)\n",
    "inference_lock = asyncio.Semaphore(1)\n",
    "\n",
    "# storage\n",
    "VOICES_DIR = os.path.abspath(\"./voices\")\n",
    "OUTPUTS_DIR = os.path.abspath(\"./outputs\")\n",
    "os.makedirs(VOICES_DIR, exist_ok=True)\n",
    "os.makedirs(OUTPUTS_DIR, exist_ok=True)\n",
    "\n",
    "# ---- FastAPI app ----\n",
    "app = FastAPI(title=\"XTTS v2 MVP\")\n",
    "\n",
    "app.add_middleware(\n",
    "    CORSMiddleware,\n",
    "    allow_origins=[\"*\"], allow_credentials=True,\n",
    "    allow_methods=[\"*\"], allow_headers=[\"*\"],\n",
    ")\n",
    "\n",
    "@app.get(\"/health\")\n",
    "def health():\n",
    "    return {\"ok\": True, \"model\": MODEL_NAME, \"sample_rate\": SAMPLE_RATE, \"device\": DEVICE}\n",
    "\n",
    "# ----- Voice management (basic) -----\n",
    "@app.post(\"/v1/voices/upload\")\n",
    "async def upload_voice(file: UploadFile = File(...)):\n",
    "    ext = os.path.splitext(file.filename or \"\")[1].lower() or \".wav\"\n",
    "    voice_id = str(uuid.uuid4())\n",
    "    path = os.path.join(VOICES_DIR, f\"{voice_id}{ext}\")\n",
    "    with open(path, \"wb\") as f:\n",
    "        f.write(await file.read())\n",
    "    return {\"voice_id\": voice_id, \"path\": path}\n",
    "\n",
    "@app.get(\"/v1/voices\")\n",
    "def list_voices():\n",
    "    items = []\n",
    "    for name in os.listdir(VOICES_DIR):\n",
    "        if name.lower().endswith((\".wav\", \".mp3\", \".flac\", \".m4a\", \".ogg\")):\n",
    "            items.append({\"voice_id\": os.path.splitext(name)[0], \"filename\": name})\n",
    "    return {\"voices\": items}\n",
    "\n",
    "def resolve_voice_path(voice_id: Optional[str]) -> Optional[str]:\n",
    "    if not voice_id:\n",
    "        return None\n",
    "    for name in os.listdir(VOICES_DIR):\n",
    "        if name.startswith(voice_id):\n",
    "            return os.path.join(VOICES_DIR, name)\n",
    "    return None\n",
    "\n",
    "# ----- REST TTS (multipart form) -----\n",
    "@app.post(\"/v1/tts\", responses={200: {\"content\": {\"audio/wav\": {}}}, 400: {\"model\": \"Error\"}})\n",
    "async def tts_rest(\n",
    "    text: str = Form(..., max_length=20000),\n",
    "    language: str = Form(\"en\"),\n",
    "    speed: float = Form(1.0),\n",
    "    voice_id: Optional[str] = Form(None),\n",
    "    speaker_wav: UploadFile = File(None),\n",
    "):\n",
    "    if not text.strip():\n",
    "        return JSONResponse({\"error\": \"text is empty\"}, status_code=400)\n",
    "\n",
    "    # pick voice: uploaded file > voice_id > None (built-in)\n",
    "    speaker_path = None\n",
    "    tmp_upload_path = None\n",
    "    if speaker_wav is not None:\n",
    "        tmp_upload_path = os.path.join(VOICES_DIR, f\"tmp-{uuid.uuid4()}.wav\")\n",
    "        with open(tmp_upload_path, \"wb\") as f:\n",
    "            f.write(await speaker_wav.read())\n",
    "        speaker_path = tmp_upload_path\n",
    "    elif voice_id:\n",
    "        speaker_path = resolve_voice_path(voice_id)\n",
    "\n",
    "    async with inference_lock:\n",
    "        audio = await asyncio.get_event_loop().run_in_executor(\n",
    "            None,\n",
    "            lambda: tts.tts(\n",
    "                text=text,\n",
    "                speaker_wav=speaker_path,\n",
    "                language=language,\n",
    "                speed=speed,\n",
    "            )\n",
    "        )\n",
    "    if tmp_upload_path and os.path.exists(tmp_upload_path):\n",
    "        try: os.remove(tmp_upload_path)\n",
    "        except: pass\n",
    "\n",
    "    wav_bytes = audio_to_wav_bytes(np.array(audio), SAMPLE_RATE)\n",
    "    return Response(content=wav_bytes, media_type=\"audio/wav\")\n",
    "\n",
    "# ----- WebSocket TTS (one-shot, returns base64 WAV) -----\n",
    "class TTSRequest(BaseModel):\n",
    "    text: str\n",
    "    language: str = \"en\"\n",
    "    speed: float = 1.0\n",
    "    voice_id: Optional[str] = None\n",
    "\n",
    "@app.websocket(\"/ws/tts\")\n",
    "async def ws_tts(ws: WebSocket):\n",
    "    await ws.accept()\n",
    "    try:\n",
    "        msg = await ws.receive_json()\n",
    "        req = TTSRequest(**msg)\n",
    "        if not req.text.strip():\n",
    "            await ws.send_json({\"error\": \"text is empty\"})\n",
    "            await ws.close()\n",
    "            return\n",
    "\n",
    "        speaker_path = resolve_voice_path(req.voice_id)\n",
    "\n",
    "        await ws.send_json({\"status\": \"started\"})\n",
    "        async with inference_lock:\n",
    "            audio = await asyncio.get_event_loop().run_in_executor(\n",
    "                None,\n",
    "                lambda: tts.tts(\n",
    "                    text=req.text,\n",
    "                    speaker_wav=speaker_path,\n",
    "                    language=req.language,\n",
    "                    speed=req.speed,\n",
    "                )\n",
    "            )\n",
    "        wav_bytes = audio_to_wav_bytes(np.array(audio), SAMPLE_RATE)\n",
    "        b64 = base64.b64encode(wav_bytes).decode(\"ascii\")\n",
    "        await ws.send_json({\n",
    "            \"status\": \"done\",\n",
    "            \"content_type\": \"audio/wav\",\n",
    "            \"sample_rate\": SAMPLE_RATE,\n",
    "            \"audio_base64\": b64,\n",
    "            \"bytes\": len(wav_bytes),\n",
    "        })\n",
    "        await ws.close()\n",
    "    except WebSocketDisconnect:\n",
    "        return\n",
    "    except Exception as e:\n",
    "        await ws.send_json({\"error\": str(e)})\n",
    "        await ws.close()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "ab8c7498-3751-414a-8ddd-2d897e81d017",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
